---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dokploy-fleet-ghcr
  namespace: vibeisland
spec:
  encryptedData:
    .dockerconfigjson: AgA9gWHbyP2mRcOnvJl+SzdDPlr5HsY3LL3cnGqmmkMJ/BFwElzMfAqy6tvZV/MKBFspPFVx9+zDtjf0BiTK9u2/wcTsR+PDzcpNRML8507G0p19Tr/7+vKedoQvYV+lutQfzh6jX/T/81Qz1CpCgvWH/l3rGSqJXfM907DV+U/hTsplnrAIoMHePQ4F3zmAylcQXdRn+tLJ3rOI/RN12arClpdEldlqNnbFL37G4x/BIZTOVoUDRQIMU3bggGGsei40yf4drO3KZg16AeR+2fe/W26VtHGB4IwriKupsJclYUtNPlFfFQ5ipXpVS7DoMNbx8KOEKassLFj11FBdZ8/Q+drFUF0LLMCfcpuUsEA4lcueM8MZNyntrRiLlVWmuunTncaRrTv+lXrKXoMfQr0lZA7lWC1CTYhxsAd9W4HwGKzDKG3etBr3Rh6t1vTeAmN6KwM4hGmw0xxijeWYijRVXxMxgz7mKUfbxxs5JBm04/Af8lkRiOaDQKYEuFE2ofwAyKIKwFwRd7k/Bk1ekLdfol1BvrLk27plOY+fe8RsD4U7gfdQQvC/Qa1hERFAOUcmcUTAFNbPV1BvNZOjDKYr8Idcp7cxPF8nTT7KKp6XFE2JCtuQf0s0y88qnrjLiLFAOGK3/7FVHve1ntkNQVmL+ynCGNNj7ZODOrsJ5NLClYZfYOOQaqLEh6fDZ+v5IgWtwmfy5y/IQExOXiFmsxcU1kAaZ12bhtJMRzjYp62+ZBOFw6o/2RksAh1zC03MJhOffmH6wf6/f6Nka4eS4vJR1Asc7kTeNSYyZ3TQDU/9jfqBXPxqFje3658UeZfGFEaCsjzc6XBlwVBcCf7I/xxKcAgLN/YWr7HqtWxEZv30VbL6NtiB9Y7iOKwiRqVtbO1PK/MAzKGsXap2LwIn34C1GSSkLvozLTUJM8DcLfvHgNmIRPfXj6rVMDI6Oil4H03gmaLTBzZxfX9YkIwhjCpcIUlU2JmI6dO1HbZO7+S7qWJvZ98pgmw/RFwOnE3zoTgy0L7YVyOMG1FOhVdwc+c/C/7j36bDKUDpD9l7ii3FKSvQmI79j5SF5GdPkUp3S36nZXYme4rGgixu/kC9DSUWg69QQ13ytjidJoR4bbl/xdl7LZq15g02Ggvtcc0iJ7Tm8Wc7QYzC6VGHCQF9StwITpmXSeCwW3l8bdP6188u7TccozOl896np2RM+aDiavFMusd7R83ztF+QQg==
  template:
    metadata:
      name: dokploy-fleet-ghcr
      namespace: vibeisland
    type: kubernetes.io/dockerconfigjson
