apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-staging-cloudflare
spec:
  acme:
    email: gateszhang92@gmai.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging-cloudflare-account-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              key: api-token
              name: cloudflare-api-token-secret
