apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vibeisland-staging
resources:
  - namespace.yaml
  - ../../base
  - sealedsecret-dokploy-fleet-ghcr.yaml
  - ingress-staging.yaml
images:
  - name: registry.144.91.77.245.sslip.io/vibeisland
    newTag: d3573a0379215c77169596e2970ab850fd32237a
