apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vibeisland-staging
resources:
  - namespace.yaml
  - ../../base
  - certificate-staging.yaml
  - issuer-staging-dns01.yaml
  - sealedsecret-cloudflare-api-token.yaml
  - sealedsecret-dokploy-fleet-ghcr.yaml
  - ingress-staging.yaml
images:
  - name: registry.144.91.77.245.sslip.io/vibeisland
    newTag: b428fe29e8ffb9afdf70a0d023953031cf9edc70
