apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: vibeisland-staging
spec:
  encryptedData:
    api-token: AgBKIElzMhGremrDmvuSAKcs+oLvHY94+rY8NUQVvGS1cGZ0lXYdKs4xvHTvJQYY71ub43hXK5GwYUmhAjiGU93fdImgeHthPi4eEzyjXEjcLeD2Duzz+JNU/5spN+6EFP5RqEwaC54FBPn9Ep3uWP7AidPM4tgozYDgKRkeLSyTwd5mjSLiJlqujlaC/O53i1s+jaSA6eYK8KhrkmwoiDBM0Dvyw3ByquMEhGttY21WK6rKbqQhhIyCHN6GG76WQbzeNmif7sBoWQfrbNnNwx02BcJpavQDr58r9JbwWVwJ5vQ1HS5l+dIV9TNE6rnaKn5+bGYBeWiq8B+saDUFoaT+5QVDutIu73OLBHYd6D6l6H9aLpDFxthnZAvj+ysEJhM/2/f53s2xy/1G6a4/OhZNVzdvW7gmOthffw2NlmTiuDZUrn6FV8ytLgHsLbpcO8vqXq6FiWOXJedLtgYU1Wy2b9mdeoRbDrlGLi7JP8uLJF6RQdgGjoJ/5Yx/Eh0uHTX8FfL0Ku5rb5mJBaHNTlfMazK6ghmIWhrkaDeegvVG1hbK35QxnIQuN+fYVSBK9J+vWzSHNJIhIRauEj62Eerm5muAQHsT1tnXpfKgD1MrV7lcJ46Qn6Rz7V/r4L/YpN0MCT/fEO2WEgKx5xlgfD+hRzWdk5AIu+NJKIkLklz4gkaT6S3MjhX4keXOtN8e7aRnj1t0s2Tav1K3Pxxun+Tjj6vhmiuL+TJfhJ6aPZUhuESyhaM0V1vO
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: vibeisland-staging
    type: Opaque
