---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dokploy-fleet-ghcr
  namespace: vibeisland-staging
spec:
  encryptedData:
    .dockerconfigjson: AgAmu3IQ77gUQZj4TAbCmG8gPVOJTp7anmq7BBeYiu3itwRr6sXql44SzjuLnb/sNIvcc4tdMngvb3VpN3avJ/tKRnjAi0VjanTkAJzYTYU42O5JGS/OerpOgQZjh6RzYtkGeIh8CFx6elcQjgg7FKlCaZs7PlKMVh7jcPbWgeisqdbj/iLPY9bZbJ6YZIu/lpEaqoPgyh4Yyljl4uaTB8ytqMYmz8M9VijR8sGqKtFj+3txkhRbter8ehSLZrgOGiASTDMMuLLEyT+LaQgXMEvw4R6E6HHTAq6+wAix9xW16s7wwvtfbvgEMp/zDBShE0C4q/40wPoLTvvrfnNJO/OV/8y3M5FiCo5MqosZFF6XspoYKJOP1+ESUAPW6LZsRWyTqR7VNzE/oVXlsevcbd0O+Dr1oIp/Zn0kdiAUTmjbC2IkXHjLCVuf2+iSuqzaE7vK58pCbRG3/+YUwMG8TEltD+Q2L+/fdiMbsZswTNAbtLznPovC5cjAzd9PnKYeazLycFUT+3r0bNdIP1g6LYPnXBMnoJIazUqIG4Be+yJ5gjnZ4koLaa8jcXQ7EQXMSn03172HdwCpv+U0fCfPJYhbkEO3zY5X56JKDBynL9eNHb6PA24y2BXxMVKQNKjqmUGbgFZslI6In3WMsz8C7zulCI6YbPD6WQ6osvmyk4KtUxtYG1gQKCqrhc6GBeeSygT0rLt7pTAnFMtpEEBstGZxLDT2EtdxgQ+eJw+SyDy+TZCEKUiAMYxFpTFiNXF5zrHNTv3il1/F9yCNy9Rc1D1kvvt7hD7+fFpCQ/kjsRqh16CuCZOx1IHCO2BpbMmpvTo0bIFGrL6NW7wenj/VIhZyljzARpYRUQm+QOMhBDZ8BP8d95qtJuePLZ8rEiW5RZFC03Bc9sMscnxLiQKuJawZRFm2paGSES0JUT8FBzTQLiw/K2Aon/787tF0C81ozkOyj2UC9g1uZwzxtoCUlvxbBpkxIHRIRADqybB6ypkPuya6vZkdChZABUw+mP1LPS43mdlORQIKrJive4rdb4XRFFvqcFCDWL3ptuyRfu8+xXWDtKUF0T1Rqz5r62vRKAUyz8fJMsGlMTZfnJEaAfzaKOvsWFfKB2N+dhOa9WZVKwSVzw36+w9Z8wU6tYHCDtQaPTZ8TW3zwcE8ry0iUYmjWZHvyVXGPuZCR/kHm/atxwBqQ3YmmnShu0QZyIQyFwAmPoTj+mn8l3HC4Q==
  template:
    metadata:
      name: dokploy-fleet-ghcr
      namespace: vibeisland-staging
    type: kubernetes.io/dockerconfigjson
