apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgC5emrjBvYjnO54fVLNzF4mO/Hx7tmJ8YVHlp5huUlvQ+2k7KGJl5s3v8QFYTgjeX2r6bHhXg8VgskepKkKU9ub6LmR8PeeqM9dsuTXnimBxHnR9QgHYVE27oAj41dWRS0FEWgyKMslYF4Mz0NSPYsJJSwxZ2JOVCzevUC/np2CH0eVvAbPwVWb/PYyDPrCa2VA4XTh8UFS7D29M2JL5AA/XSWmOO26z6oHEnHOA0D7kjtw0go3Da77fzelSDgbxfNHOi6/OzEtpt0SHUTRLNleMai8X2nZ/kE/10lAyfldHJGFkH8ahgWXzHwTgLZE3Urtld+xPhcSrIaeBAvvBCiA8gSB9PvWljjXT5uZsKdzoR9nJja9UtX8/ExVSCmboZ05yZg2pGJVZCLYNAQWK571o+8unV0HGJk9yvnP9sJp5VKef2oZa9jpJyD0KxbHu3fDWYcI1B4k3jeKN+h/uaYZRfLhWYVSqs3vivCtO1haTkOOad7HxxFcQqHJLlB9PEiMG6kjEUMLGxydjoWLa+TzcGRynAWzIGnHHCHEIp6LmXhqpmJX0DhAWUkW7CKYsRKgmFEjSdBEGmC6byJ8GdRVJCermPVIfJK9YHuLcnNTAQhmcq3VfxSmcISCarORSm/P2pc1qWU/fX+MsO7CqCZ6IEoSJCUsPtJ92FkxMYtErWs8UTVj+zvnDNi1Dy28qsCxuckTbdwudsupEFfJePk7iloGXAUBpnDLo6XwYZSCbprIT9lqWYza
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
