apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vibeisland
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: vibeisland
  source:
    repoURL: https://github.com/gateszhangc/vibeisland.git
    targetRevision: main
    path: deploy/k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: vibeisland
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
