apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vibeisland-live
  annotations:
    acme.cert-manager.io/http01-edit-in-place: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    cert-manager.io/issue-temporary-certificate: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - secretName: vibeisland-live-tls
      hosts:
        - vibeisland.lol
  rules:
    - host: vibeisland.lol
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vibeisland
                port:
                  number: 80
