apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vibeisland-live
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - secretName: vibeisland-live-tls
      hosts:
        - vibeisland.lol
        - www.vibeisland.lol
  rules:
    - host: vibeisland.lol
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vibeisland
                port:
                  number: 80
