apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - certificate-live.yaml
  - ingress-live.yaml
  - ingress-preview.yaml
  - issuer-live-dns01.yaml
  - sealedsecret-cloudflare-api-token.yaml
images:
  - name: registry.144.91.77.245.sslip.io/vibeisland
    newTag: d3573a0379215c77169596e2970ab850fd32237a
