apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vibeisland
resources:
  - namespace.yaml
  - ../../base
  - sealedsecret-dokploy-fleet-ghcr.yaml
  - certificate-live.yaml
  - ingress-live.yaml
  - ingress-preview.yaml
  - issuer-live-dns01.yaml
  - sealedsecret-cloudflare-api-token.yaml
images:
  - name: registry.144.91.77.245.sslip.io/vibeisland
    newTag: dd441a0c35e083b4af9ddd7805d3f8166d87812e
