apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - certificate-live.yaml
  - ingress-live.yaml
  - ingress-preview.yaml
  - issuer-live-dns01.yaml
  - sealedsecret-cloudflare-api-token.yaml
images:
  - name: registry.144.91.77.245.sslip.io/vibeisland
    newTag: c91981fca58d58aaa0e2a2fca65ffffdfd68a339
