apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: vibeisland
spec:
  encryptedData:
    api-token: AgCDSr8habv6DimQPc0XkfGpFnwH5ABpmJg6m8aWE4snMO2DOPM9CTBaTqbbujhh0RBsX1w0IISMRKDEzT+TDGZUMJAFBDwdizIlsb4mNtTt/wWXNYNe8WOrEw5EoJgDGwH8UlfZyI5IC2R2z9At9eyvulLuMWpz+HXoMzhb4M1zpDlDjpaxZFmNOyhKALbmpp/CQvnzhAb1TwJ5UmIN6OCb2DXbG3RoY4dI14E4rm/uOeBIzlRMQVKFqv2AAbpmDdhL5S7x8R2PBpQnPtlTZxwnrgOEpQStXsca7AJQ617byDs/ifL7NH/ovCsE8bEGUIv9/6oepvVIdPn0bGUh1RXaPfSlVv8jAbWXhRm/44tTK2V1A1pZRCqjsWENKdDRtd2gly6IOy0X475r4zPOB0O+mxTfEbbA5uHQFyzDEbAHoCx70WjzMB/o1ss+U9mwa43dpQPFZYk8vPNr3vErr+YV+8BIXlhi1dl31lcTWjAFx4ZNvXeqoJNwJBLr+ukKIGwMy72IK5IAJXAjqTOxdiXuzJgPvgwAR7SuzQ7CBl6p0GtXXJXNUBizPQE48z8GM+N43wxMfGh/9OO4xNzLyCV1AuypxIYum6bj+QCbeBuPlFpuOvckNKbFr27sPP2yvTHoV3NX0f397Mj5bOcPpef8L1eUY7HwEGMM0+Z8HLJrDuJI+m+IAF9OeT0V9eiPXrlHLGvRg4z1Qdx9EWluVjJS4/AMIjaTmNybqqDqgomaFPqVAlaPlKPJ
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: vibeisland
